# Generated by Django 5.1.4 on 2024-12-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='notes',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Yoga', 'Yoga'), ('HIIT', 'HIIT'), ('Pilates', 'Pilates'), ('Other', 'Other')], max_length=100),
        ),
    ]
