# Generated by Django 5.1.4 on 2024-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_nutritionlog_meal_type_alter_nutritionlog_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='food_item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='meal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
