# Generated by Django 5.1.4 on 2024-12-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_nutritionlog_calories_alter_nutritionlog_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='food_item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
